import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Logo from "@/components/icons/Logo";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased bg-bold-background font-[family-name:var(--font-geist-sans)] flex flex-col gap-5`}
      >
        <header className="flex justify-center bg-bold-gradient px-8 py-6">
          <div className="flex flex-1 items-center  justify-between">
            <Logo />
            <ul className="flex  gap-6 text-white">
              <li>
                <a href="#" className="hover:underline">
                  Mi negocio
                </a>
              </li>
              <li>
                <a href="#" className="hover:underline">
                  Ayuda
                </a>
              </li>
            </ul>
          </div>
        </header>
        <main className="flex flex-col gap-5">{children}</main>
      </body>
    </html>
  );
}
